spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: gs-yarn-basic
        applicationDir: /app/gs-yarn-basic/
        client:
            files:
              - "file:gs-yarn-dist/target/gs-yarn-dist/gs-yarn-container.jar"
              - "file:gs-yarn-dist/target/gs-yarn-dist/gs-yarn-appmaster.jar"
            launchcontext:
                archiveFile: gs-yarn-appmaster.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: gs-yarn-container.jar